### ISSUE TITLE
Bug: 구글 로그인 리다이렉트에서 토큰이 넘어오지 않음 

### ISSUE THREAD

**Issue by hocaron** [So-Woo-Ju/sowooju-api-server#13]
- 구글 로그인 시 토큰이 넘어오지 않고 있습니다.
- 소셜 로그인 docs tag가 없습니다.

**Comment by Sohyun-Dev** [comment]
![image](https://user-images.githubusercontent.com/71393695/149857085-001f32cf-6f23-4009-bc19-e6a19b786f74.png)
- 리다이렉트 URL 부분은 다음과 같이 작성했는데 혹시 몰라 사진 첨부합니다.

**Comment by hocaron** [comment]
확인했습니다!
